In [3]:
import numpy as np  
  
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  

print("Please write the elements of the first matrix in a single line and separated by a space: ")  
elements1 = list(map(int, input().split()))  

print("Please write the elements of the second matrix in a single line and separated by a space: ")  
elements2 = list(map(int, input().split()))  
 
matrix1 = np.array(elements1).reshape(Rows, Columns)  
print(matrix1) 

matrix2 = np.array(elements2).reshape(Rows, Columns)  
print(matrix2) 


Give the number of rows: 2
Give the number of columns: 2


Please write the elements of the first matrix in a single line and separated by a space: 


 1 2 3 4 


Please write the elements of the second matrix in a single line and separated by a space: 


 1 4 5 6 


[[1 2]
 [3 4]]
[[1 4]
 [5 6]]


In [4]:
dotProduct=np.dot(matrix1,matrix2)
print(dotProduct)

[[11 16]
 [23 36]]


In [5]:
traspose=np.transpose(matrix1)
print(traspose)

[[1 3]
 [2 4]]


In [6]:
trace=np.trace(matrix1)
print(trace)

5


In [7]:
rank=np.linalg.matrix_rank(matrix1)
print(rank)

2


In [8]:
determinant=np.linalg.det(matrix1)
print(determinant)

-2.0000000000000004


In [9]:
inverse=np.linalg.inv(matrix1)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
eignvalue,eigenvector=np.linalg.eig(matrix1)
print("Eigen value : ",eignvalue)
print("Eigen vector : ",eigenvector)

Eigen value :  [-0.37228132  5.37228132]
Eigen vector :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
