In [9]:
# 1. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
import numpy as np
array_1 = np.array([1, 2, 3])
array_2 = np.array([1, 3, 2])
print('Array 1:', array_1)
print('Array 2:', array_2)
print('Greater:', np.greater(array_1, array_2))
print('Greater Equal:', np.greater_equal(array_1, array_2))
print('Equal:', np.equal(array_1, array_2))
print('Less:', np.less(array_1, array_2))
print('Less Equal:', np.less_equal(array_1, array_2))

Array 1: [1 2 3]
Array 2: [1 3 2]
Greater: [False False  True]
Greater Equal: [ True False  True]
Equal: [ True False False]
Less: [False  True False]
Less Equal: [ True  True False]


In [2]:
# 2. Write a NumPy program to create an array of all the even integers from 30 to 70.
array_3 = np.arange(30, 70, 2)
print('Even numbers from 30 to 70:', array_3)


Even numbers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [3]:
# 3. Write a NumPy program to create a 3x3 identity matrix.
array_4 = np.identity(3, int)
print('3x3 identity matrix:', array_4)

3x3 identity matrix: [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
# 4. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
array_5 = np.arange(21)
print("Original vector:")
print(array_5)
print("After changing the sign of the numbers in the range from 9 to 15:")
array_5[(array_5 >= 9) & (array_5 <= 15)] *= -1
print(array_5)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [11]:
# 5. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5
value = np.arange(1, 6)
array_6 = np.diag(value)
print('5x5 Zero matrix with diagonal 1,2 3, 4, 5:\n', array_6)

5x5 Zero matrix with diagonal 1,2 3, 4, 5:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
# 6. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
array_7 = [[1,2,3],[4,5,6]]
print('Array:', array_7)
print('Sum:', np.sum(array_7))
print('Sum Row:', np.sum(array_7, axis=1))
print('Sum Col:', np.sum(array_7, axis=0))

Array: [[1, 2, 3], [4, 5, 6]]
Sum: 21
Sum Row: [ 6 15]
Sum Col: [5 7 9]


In [7]:
# 7. Write a NumPy program to save a given array to a text file and load it.
import numpy as np
np.savetxt('1array.txt',array_7)
print(np.loadtxt('1array.txt').astype(np.int64))



[[1 2 3]
 [4 5 6]]


In [10]:
# 8. Write a NumPy program to check whether two arrays are equal (element wise) or not.
print('Array 1:', array_1)
print('Array 2:', array_2)
if np.array_equal(array_1, array_2):
  print('Arrays are equal')
else:
  print('Arrays are not equal')

Array 1: [1 2 3]
Array 2: [1 3 2]
Arrays are not equal


In [26]:
# 9. Write a NumPy program to create a 4x4 array with random values, now create a new arrayfrom the said array swapping first and last rows.
np.random.seed(42)
a = np.random.rand(4,4)
print(f'random array \n{a}')
a[[0,3]] = a[[3,0]]
print(f'Swapped array\n {a}')

random array 
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]
Swapped array
 [[0.83244264 0.21233911 0.18182497 0.18340451]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.37454012 0.95071431 0.73199394 0.59865848]]


In [27]:
# 10. Write a NumPy program to multiply two given arrays of same size element-by-element
a = np.arange(1, 6)
b = np.arange(6, 11)
print('a:', a)
print('b:', b)
print('axb:', a*b)

a: [1 2 3 4 5]
b: [ 6  7  8  9 10]
axb: [ 6 14 24 36 50]
