In [18]:
# ?read array from user
import numpy as np
# r,c=2,2
# m1 = []
# for i in range(r):
#   ele = [int(input(f'Enter element {i+1} {j+1}:')) for j in range(c)]
#   m1.append(ele)
# print(m1)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Dot product of a and b
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

# Transpose of a (reshaped to a 2D array)
transpose_a = np.transpose(a.reshape(1, -1))
print("Transpose of a:", transpose_a)

# Trace of a
trace_a = np.trace(a.reshape(1, -1))
print("Trace of a:", trace_a)

# Rank of a matrix
rank_a = np.linalg.matrix_rank(a.reshape(1, -1))
print("Rank of a:", rank_a)

# Determinant of a
determinant_a = np.linalg.det(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print("Determinant of a:", determinant_a)

# Inverse of a
# inverse_a = np.linalg.inv(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
# print("Inverse of a:")
# print(inverse_a)

# Eigenvalues and eigenvectors of a
eigenvalues, eigenvectors = np.linalg.eig(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)




Dot Product: 32
Transpose of a: [[1]
 [2]
 [3]]
Trace of a: 1
Rank of a: 1
Determinant of a: 0.0
Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
